export const animals = [
  "Bumble bee",
  "Bat",
  "Beluga whale",
  "Blue whale",
  "Brown bear",
  "Buffalo",
  "Bison",
  "Baboon",
  "Sun bear",
  "Beaver",
  "Black bear",
  "Blue whale",
  "Boa constrictor",
  "Butterfly",
  "Camel",
  "Capybara",
  "Cassowary",
  "Chameleon",
  "Chinchilla",
  "Chimpanzee",
  "Chicken",
  "Chinstrap penguin",
  "Cockatoo",
  "Condor",
  "Crocodile",
  "Dolphin",
  "Donkey",
  "Duck",
  "Dove",
  "Dragonfly",
  "Dragon lizard",
  "Eagle",
  "Elephant",
  "Emu",
  "Falcon",
  "Ferret",
  "Finch",
  "Flamingo",
  "Flying squirrel",
  "Fox",
  "Giraffe",
  "Goose",
  "Gorilla",
  "Grasshopper",
  "Guinea pig",
  "Guppy",
  "Hedgehog",
  "Highland cow",
  "Hippo",
  "Hippopotamus",
  "Horse",
  "Hummingbird",
  "Hare",
  "Hornbill",
  "Hyena",
  "Ibis",
  "Iguana",
  "Jaguar",
  "Jellyfish",
  "Kingfisher",
  "Koala",
  "Komodo dragon",
  "Leopard",
  "Lemming",
  "Lemur",
  "Lion",
  "Llama",
  "Lobster",
  "Macaw",
  "Magpie",
  "Manatee",
  "Mandrill",
  "Manta ray",
  "Meerkat",
  "Mole",
  "Moose",
  "Monitor lizard",
  "Newt",
  "Narwhal",
  "Octopus",
  "Ostrich",
  "Otter",
  "Owl",
  "Osprey",
  "Orca",
  "Ostrich",
  "Panda",
  "Panther",
  "Parrot",
  "Pelican",
  "Penguin",
  "Pigeon",
  "Platypus",
  "Pony",
  "Polar bear",
  "Prawn",
  "Quail",
  "Quokka",
  "Rabbit",
  "Raccoon",
  "Rat",
  "Reindeer",
  "Rhinoceros",
  "Rhino",
  "Robin",
  "Raven",
  "Salmon",
  "Seahorse",
  "Seal",
  "Sea lion",
  "Seagull",
  "Skunk",
  "Sloth",
  "Slug",
  "Snail",
  "Snow leopard",
  "Snowy owl",
  "Sparrow",
  "Spider",
  "Squirrel",
  "Stingray",
  "Stork",
  "Starfish",
  "Starling",
  "Stingray",
  "Swordfish",
  "Swallow",
  "Tapir",
  "Tasmanian devil",
  "Tiger",
  "Tortoise",
  "Toucan",
  "Turtle",
  "Vampire squid",
  "Vole",
  "Walrus",
  "Warthog",
  "Weasel",
  "Whale",
  "Wolf",
  "Woodpecker",
  "Wolverine",
  "Yak",
  "Zebra",
];

export const places = [
  "In a cave",
  "At the beach",
  "In a bakery",
  "In space",
  "At a tea party",
  "On a mountain",
  "Inside a lighthouse",
  "In a flower field",
  "At the library",
  "In the rain",
  "Having a picnic",
  "Painting a portrait",
  "Riding a bicycle",
  "Dancing in the rain",
  "Flying kites",
  "Building a sandcastle",
  "Playing chess",
  "Stargazing",
  "Baking cookies",
  "Reading a map",
  "Camping in the forest",
  "Playing video games",
  "Hosting a tea party",
  "Playing musical instruments",
  "Gardening",
  "Ice skating",
  "Skiing down a mountain",
  "Surfing",
  "Exploring a cave",
  "Taking a selfie",
  "Walking through a city",
  "Shopping at a market",
  "Cooking dinner",
  "Watching a film",
  "Playing rugby",
  "Building a robot",
  "Doing yoga",
  "Painting road markings",
  "Writing a story",
  "Exploring space",
  "Climbing a mountain",
  "Sailing a boat",
  "Fishing by a swamp",
  "Having a snowball fight",
  "Decorating a cake",
  "Playing cards",
  "Doing magic tricks",
  "Learning French",
  "Building a treehouse",
  "Playing hide and seek",
  "Visiting a museum",
  "Driving a car",
  "Riding a train",
  "Flying an aeroplane",
  "Walking a tightrope",
  "Performing on stage",
  "Taking photographs",
  "Making pottery",
  "Knitting a scarf",
  "Sewing clothes",
  "Exploring a jungle",
  "Treasure hunting",
  "Digging for fossils",
  "Playing in a band",
  "Doing science experiments",
  "Mixing potions",
  "Training for a race",
  "Lifting weights",
  "Meditating",
  "Doing martial arts",
  "Playing basketball",
  "Playing tennis",
  "Skateboarding",
  "Roller skating",
  "Riding a scooter",
  "Playing in the snow",
  "Sunbathing",
  "Having a barbecue",
  "Roasting marshmallows",
  "Telling ghost stories",
  "Exploring a haunted house",
  "Time travelling",
  "Fighting dragons",
  "Casting spells",
  "Running a café",
  "Working in a bakery",
  "Delivering post",
  "Litter picking",
  "Cleaning a house",
  "Babysitting",
  "Teaching a class",
  "Studying in a library",
  "Writing a letter",
  "Sending messages",
  "Playing with toys",
  "Building a bridge",
  "Solving puzzles",
  "Playing board games",
  "Hosting a party",
  "Baking bread",
];